### ISSUE TITLE
Windows 10 VM problem

### ISSUE THREAD

**Issue by MinLiWu** [DualCoder/vgpu_unlock#49]
Hi,
I used vgpu_unlock to successfully virtualize the 2080s, and also successfully turned on the windows 10 VM with vGPU and passed the license verification. But since my VM added the mdev of vGPU, it feels a bit lagging, and it feels like there is something wrong. I have tried B-series and Q-series, and disables frame rate limiting.

Have you encountered a similar problem?
Can you also share the full XML file of your VM?
How do you connect to the VM with vGPU? I use RDP and TightVNC.

**Comment by DualCoder** [comment]
> But since my VM added the mdev of vGPU, it feels a bit lagging, and it feels like there is something wrong.

It is very difficult to say if something is wrong. What are you comparing against? The VM before adding the vGPU?

> Have you encountered a similar problem?

Since I don't fully understand the problem, it is difficult to say. But I did have CPU related performance issues, which of course slowed down the entire VM, but this was due to a misconfiguration of the VM itself and unrelated to vGPU. 

> Can you also share the full XML file of your VM?

No, at least not right now.

> How do you connect to the VM with vGPU? I use RDP and TightVNC.

I have installed the TightVNC server into a Windows VM as sort of a backup connection that "just works", but using it is very laggy, and I think that is to be expected with VNC, it is not a performance optimised system.

I have tried RDP too, and my subjective opinion is that it works equally well to run RDP to the VM, as it does to run RDP to a bare metal Windows machine. So clearly an improvement over VNC with regards to performance.

Other than that I have run LookingGlass (https://github.com/gnif/LookingGlass) which offers the best image quality and latency of everything mentioned thus far, but it is not a remote solution and is intended to output the image on a second GPU in the same system.

Here are some random performance optimisations off the top of my head:

* Enable CPU features in the VM configuration, by default QEMU uses a compatibility optimised feature set. "Copy host configuration" should be a good option here.
* Run CPU and RAM benchmarks to identify performance issues with these components, performance issues here will slow down the entire VM. If the performance is lacking, check the CPU socket/core/thread configuration, any CPU pinning, hugepages etc.
* Make sure that the VM is actually using the vGPU for graphics related tasks, the VM should be configured to output to the NVIDIA virtual display. If applicable, remove any unused virtual graphics device from the VM config.
* Configure any Windows VM for 'high performace" and disable any unused windows stuff (cortana, defender, etc).
* Also for Windows VMs, enable Hyper-V optimisations in the VM configuration.

**Comment by MinLiWu** [comment]
I found the problem from the log that appear "NVOS status 0x65", "VGPU message 22 failed", " XID 43 detected on physical_chid:0x20" and "Timeout detection and recovery (TDR) completed".
It seems to be caused by the version of vGPU manager. I used the lastest version 12.2 before. 
Since I reinstalled the old version of vGPU Manager, everything is ok.
