### ISSUE TITLE
Support for GA102 Chips

### ISSUE THREAD

**Issue by jesuspabloalfaro** [DualCoder/vgpu_unlock#88]
I'm not quite sure where to ask this question so please excuse me if this is not the right place. I see that GA102 GPU Chips are not supported by vGPU and I was wondering if there were any future plans to compile support for these newer chips or not. Thank you for your awesome contributions to the vGPU community!

**Comment by cruzzer** [comment]
In the description at the top of the project description it states:

 - "Ampere support is currently a work in progress"

Since GA102 is an Ampere card, it is also in Progress. Somewhere in the details I read that Ampere cards work a little different and might require a new approach to make them work.
